reFactorPrj/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using reFactorPrj.Models;
using System.IO;

namespace reFactorPrj.Controllers
{
    public class RecipesController : Controller
    {
        private reModel db = new reModel();
        private int PageSize = 9;

        // GET: Recipes
        // 食譜頁面
        public ActionResult Index(int Page = 0)
        {
            Page = Page - 1 > 0 ? Page - 1 : 0;

            return View(db.tRecipe.OrderByDescending(m => m.fR_Id).ToList().ToPagedList(Page, PageSize));
        }

        // 搜尋食譜
        [HttpPost]
        public ActionResult Search(string searchMenu, int Page = 0)
        {
            Page = Page - 1 > 0 ? Page - 1 : 0;
            // AsQueryable 產生SQL 的 where語法
            var result = db.tRecipe.OrderByDescending(m => m.fR_Id).AsQueryable();
            if (!String.IsNullOrEmpty(searchMenu))
            {
                result = result.Where(s => s.fR_Menu.Contains(searchMenu));
            }

            if (result.Any())
            {
                return View("Index", result.ToList().ToPagedList(Page, PageSize));
            }
            else
            {
                TempData["Message"] = "查無結果";
                return RedirectToAction("Index");
            }
        }

        // 食譜細項
        public ActionResult Details(int Id)
        {
            tRecipe tRecipe = db.tRecipe.Find(Id);
            return View(tRecipe);
        }

        // 加入購物車
        public ActionResult AddToCart(int Id)
        {
            // loginUserInfo
            var UserInfo = db.tMembers.Find(Session["isLogin"]);
            if (UserInfo == null)
            {
                // 如果沒使用者 踢掉
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<int> RecipeIdList = (List<int>)Session["RecipeIdList"];
                if (RecipeIdList == null)
                {
                    RecipeIdList = new List<int>();
                }
                RecipeIdList.Add(Id);
                Session["RecipeIdList"] = RecipeIdList;

                return RedirectToAction("Index", "Carts");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

reFactorPrj/Views/Recipes/Details.cshtml
@model reFactorPrj.Models.tRecipe
@{
    ViewBag.Title = "食譜明細 - ";
}

@*@{
        string a = ViewBag.fR_Menu.ToString();
        a += ".jpg";
    }*@
@{ 
    string a = Model.fR_Menu.ToString();
    a += ".jpg";
}

<style>
    #food_img {
        width: 100%;
        height: 250%;
        margin-top: 20px;
        object-fit: cover;
    }

    .container3 {
        width: 100%;
        text-align: left;
        margin-bottom: 30px;
        margin-top: 30px;
    }

    .container2 {
        width: 100%;
    }

    h3 {
        text-align: center;
    }

    h5 {
        font-size: 18px;
        font-weight: bold;
    }

    #love {
        width: 10px;
        height: 10px;
        color: rgb(219, 9, 9);
    }

    #cart {
        height: 30px;
        width: 30px;
        position: relative;
        left: 80%;
    }

    .mt-1 {
        margin-top: 30px;
    }

    .contact {
        width: 20px;
        height: 20px;
        margin-top: 20px;
    }

        .contact:hover {
            transform: scale(1.5);
        }

    .addcart {
        margin-top: 5px;
        margin-left: 10px;
    }

        .addcart a {
            text-decoration: none;
        }

    .heart {
        color: orangered;
    }
</style>


<div class="container mt-1">
    <div class="row">
        <div class="col l5 s12">
            <div class="container3">
                <h4 class="center-align">
                    @Model.fR_Menu
                </h4>
                <img id="food_img" src="~/images/foodpic/@a" alt="food">
                <h5>
                    @if (Session["Member"] == null)
                    {
                        <a OnClick="return confirm(" &#39;請先登入會員&#39;")" href="@Url.Action("Login","Login")" style="color:black;">
                            加入我的最愛<i class="small material-icons heart contact">favorite</i>
                        </a>
                    }
                    else
                    {
                        <a OnClick="return confirm(" &#39;成功加入我的最愛&#39;")" href="@Url.Action("MyFavorite","Home")?pid=@Model.fR_Id" style="color:black;">
                            加入我的最愛<i class="small material-icons heart contact">favorite</i>
                        </a>
                    }
                </h5>
                <h5>寄給朋友  <img class="contact" src="~/images/RecipeDetails/messsnger.png" alt="facebook"></h5>
                <h5>分享  <img class="contact" src="~/images/RecipeDetails/line.png" alt="line"></h5>
            </div>
        </div>

        <div class="col l7 s12 push-l1">
            <div class="container2">
                <h5>
                    食材
                </h5>
                <hr>
                <table>
                    <tr>
                        <th>
                            品項
                        </th>
                        <th>
                            用量
                        </th>
                        <th>
                            單位
                        </th>
                    </tr>
                    @*@for (int i = 0; i < Model.Ingredients.Count; i++)
        {
            <tr>
                <td>
                    @Model.Ingredients[i].fRD_Ingredients
                </td>
                <td>
                    @Model.RecipeDetails[i].fRD_Dos
                </td>
                <td>
                    @Model.Ingredients[i].fRD_Unit
                </td>
            </tr>
        }*@
                    @foreach (var item in Model.tRecipeDetail)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.fRD_Dos
                            </td>
                            <td>
                                @item.fRD_Unit
                            </td>
                        </tr>
                    }
                </table>
                @if (Session["isLogin"] == null)
                {
                 <div class="addcart">
                    <a OnClick="return confirm(&#39;請先登入會員&#39;)" href="@Url.Action("Login","Members")" style="color:black;">
                        <i id="cart" class="small material-icons">add_shopping_cart</i>
                    </a>
                 </div>
                }
                else
                {
                    <div class="addcart">
                        <a OnClick="return confirm(&#39;確定加入購物車嗎???&#39;)" href="@Url.Action("AddToCart")?id=@Model.fR_Id">
                            <i id="cart" class="small material-icons">add_shopping_cart</i>
                        </a>
                    </div>
                }
                <br />
            </div>
        </div>

    </div>

    <div class="container3">
        <h5>
            步驟
        </h5>
        <hr>
        <span style="white-space: pre-line;" line-height="2" ;>@Model.fR_Do</span>
    </div>
</div>

reFactorPrj/Views/Recipes/Index.cshtml
@model PagedList<reFactorPrj.Models.tRecipe>

<style>
    .mySearch .row {
        margin-bottom: 0px;
        margin-top: 20px;
    }

    .pagination {
        display: flex;
        align-items: center;
        justify-content: center;
    }

        .pagination > span, .pagination > a {
            padding: 10px;
            font-size: 18px;
        }

            .pagination > span:hover, .pagination > a:hover {
                border-radius: 5px;
                background-color: #eee;
            }

    .tags-padding {
        padding-left: 56px;
        padding-right: 10px;
    }

    .card-image img {
        transform: scale(1, 1);
        transition: all 1s ease-out;
        object-fit: cover;
    }

        .card-image img:hover {
            transform: scale(1.2, 1.2);
        }

    .card {
        transition: all 0.5s;
    }

        .card:hover {
            transform: translateY(-10px);
            transition: all 0.5s;
        }

    /*愛心*/
    .heart {
        position: absolute;
        right: 0px;
        margin-right: 10px;
        color: orangered;
        z-index: 20;
    }

    .searchbox {
        box-shadow: 5px 5px 20px rgba(0, 0, 0, 0.3);
        padding: 30px;
        margin-bottom: 20px;
    }

    .mt-2 {
        margin-top: 20px
    }
</style>

@*<link href="~/Content/PagedList.css" rel="stylesheet" />*@

<div class="container mySearch">
    <h4 class="center-align">食譜</h4>
    <div class="row">
        <div class="col s12">
            <div class="input-field col s12">
                @using (Html.BeginForm("Search", "Recipes"))
                {
                    <div class="searchbox">
                        <div class="file-path-wrapper">
                            <input type="text" name="searchMenu" value="" placeholder="請輸入要查詢的食譜，EX:白醬..." />
                        </div>
                        <div class="center-align mt-2">
                            <button class="waves-effect waves-light btn" type="submit">搜尋</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<!--card-->
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            string photo = "";
            if (Model != null)
            {
                photo = item.fR_Menu.ToString() + ".jpg";
            }

            <div class="col s12 l4">
                <div class="card hoverable">
                    <div class="card-image waves-effect waves-block waves-light">
                        <a href="@Url.Action("Details","Recipes")?id=@item.fR_Id">
                            <img class="activator"
                                 src="~/images/foodpic/@photo" width="400" height="300" />
                        </a>
                    </div>
                    <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">
                            @Html.DisplayFor(modelItem => item.fR_Menu)
                        </span>
                        <p>
                            <a href="@Url.Action("Details","Recipes")?id=@item.fR_Id">查看完整資訊</a>
                            @if (Session["Member"] == null)
                            {

                                <a OnClick="return confirm(" &#39;請先登入會員&#39;")" href="@Url.Action("Login","Members")" class="tooltipped heart" data-tooltip="加入我的最愛">
                                    <i class="small material-icons heart">favorite</i>
                                </a>

                            }
                            else
                            {
                                <a OnClick="return confirm(" &#39;成功加入我的最愛&#39;")" href="@Url.Action("MyFavorite","Home")?pid=@item.fR_Id" class="tooltipped heart" data-tooltip="加入我的最愛">
                                    <i class="small material-icons heart">favorite</i>
                                </a>
                            }
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="center-align pagination">
        @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount)
    </div>
</div>

@if (TempData["message"] != null)
{
    <script>
        alert("查無資料")
    </script>
}

<script>
    (function ($) {
        $(function () {
            $('.parallax').parallax();

            //愛心提示訊息
            $('.tooltipped').tooltip();

            //有用到jQuery的功能就寫在這
        }); // end of document ready
    })(jQuery); // end of jQuery name space
</script>